config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#public_recipes"

  # or we can have a homepage at the start: "users#index"

  resources :recipes, only: [:index, :show, :new, :create] do 
    member do
      get :delete
    end
    resources :recipe_food, only: [:new, :create, :destroy]
  end
  resources :foods, only: [:index, :show, :new]
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :inventory, only: [:index, :new, :create, :show, :destroy] do
    resources :inventory_food, only: [:new, :create, :destroy]
  end
  resources :shopping_list, only: [:index]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food
  has_many :foods, through: :recipe_food

  validates_presence_of :name, :cooking_time, :preparation_time, :description, :public
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # before_action :authenticate_user!, only: %i[create destroy]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: :public_recipes

  def index
    @user = current_user
    @recipes = @user&.recipes
  end

  def show
    @recipe = Recipe.find(params[:id] || params[:recipe_id])
    @inventory_data = Inventory.all
    return if params[:inventory_id].nil?

    recipe_food_list = RecipeFood.where(recipe_id: params[:id] || params[:recipe_id]).pluck(:food_id)
    @if_foods_list = InventoryFood.where(inventory_id: params[:inventory_id]).pluck(:food_id)
    @inventory = Inventory.find(params[:inventory_id])
    diff = recipe_food_list - @if_foods_list
    @meta_data = Food.where(id: diff).pluck(:id, :name, :measurement_unit, :price)
    @total_price = 0
    @meta_data.each do |item|
      @total_price += RecipeFood.find_by(food_id: item[0]).quanity * item[3]
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully!'
    else
      render new, status: :unprocessable_entity, alert: 'An error has occurred while creating the new recipe'
    end
  end

  def delete
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe deleted Successfully'
    else
      redirect_to root, alert: 'Could not delete recipe'
    end
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user).all.where(public: true).order(created_at: :desc)
    render :public_recipes
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="recipe-list">
  <div>
    <%= link_to "New Recipe", new_recipe_path, class:"btn margin" %>
  </div>
  <ul>
    <% if @recipes&.empty? %>
      <p>No recipes to show!</p>
      <%else%>
      <% @recipes&.each do |recipe| %>
      <li class="recipe-card">
        <h1><%= link_to recipe.name, recipe_path(recipe.id), class:"recipe-title" %></h1>
        <p><%= recipe.description %></p>
        <%= link_to('Remove', delete_recipe_path(recipe), class:"btn") %>
      <li>
      <% end %>
    <%end%>
  </ul>
</div>

app/views/recipes/new.html.erb
<div class="form-container">
  <%= form_with model: @recipe, url: recipes_path, class: "recipe-form" do |form| %>
      <%= form.text_field :name, placeholder: 'Name'%>
      <br>
      <%= form.number_field :preparation_time, placeholder: 'Preparation Time' %>
      <br>
      <%= form.number_field :cooking_time, placeholder: 'Cooking Time' %>
      <br>
      <%= form.text_area :description, placeholder: 'Description', class: "text_area" %>
      <br>
      <%= form.label :public, "Public recipe" %>
      <%= form.select :public, options_for_select([true, false]) %>
      <br>
      <%= form.submit "Add", class: "btn" %>
    <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<section class="recipe-list">
  <h1>PUBLIC RECIPES</h1>
  <% @public_recipes&.each do |recipe| %>
    <div class="recipe-card">
      <div>
        <h3 calss="recipe-title"><%= link_to recipe.name, recipe_path(recipe.id), class:"recipe-title"%></h3>
        <div>By <%= recipe.user.name %></div>
      </div>
      <div>
        <div>Total food items: <%= recipe.foods.count %></div>
        <div>Price: $<%= recipe.foods.sum(:price) %></div>
      </div>
    </div>
  <% end %>
</section>

app/views/recipes/show.html.erb
<section class="recipe-list">
  <h1><%= @recipe.name %></h1>
  <div class="recipe-detail">
    <div>
      <p>Preparation Time: <%= @recipe.preparation_time %></p>
      <p>Cooking Time: <%= @recipe.cooking_time %></p>
    </div>
    <div>
      <label>Public</label>
      <label class="switch">
        <input type="checkbox">
        <span class="slider round"></span>
      </label>
    </div>
  </div>
  <div class="recipe-detail">
    <button type="button" class="long-btn" data-bs-toggle="modal" data-bs-target="#shoppingModal">Generate Shopping List</button>
    <%= button_to "Add Ingredients", new_recipe_recipe_food_path(@recipe.id) , method: :get, class: "long-btn" %>
  </div>

  <br>
  <h3 style="text-align: center">Ingredient List</h3>

  <table id = "customers">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
      <% if @recipe.recipe_food.any? %>
        <% @recipe.recipe_food.each do |recipe_food| %>
          <tr>
            <td> <%= recipe_food.name %> </td>
            <td> <%= "#{recipe_food.quanity } #{recipe_food.current_food.measurement_unit}" %> </td>
            <td> $<%= recipe_food.current_food.price * recipe_food.quanity  %> </td>
            <td>
              <%= button_to "Delete Food", "/recipes/#{@recipe.id}/recipe_food/#{recipe_food.id}" , method: :delete, class: "long-btn" %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td> No food has been added to this recipe </td>
        </tr>
      <% end %>
    </thead>
  </table>
</section>
<%= render "layouts/shopping_list" %>

<!-- Modal -->
<div class="modal fade" id="shoppingModal" tabindex="-1" aria-labelledby="shoppingModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="shoppingModalLabel">Shopping</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h3 style="text-align: center">Generating Shopping List</h3>
        <p>Choose an inventory to use</p>
        <div class="inventory-choose">
          <select class="form-select" aria-label="Default select example" style="width: 50%" id="invetory_list">
            <option selected>Select Inventory</option>
            <% @inventory_data.each do |item| %>
              <option value=<%= item.id %>><%= item.name %></option>
            <% end %>
          </select>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="generate" onclick="window.location.href = '<%= recipe_path(@recipe) %>/?inventory_id='+document.getElementById('invetory_list').value">Generate</button>
      </div>
    </div>
  </div>
</div>