config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#public_recipes"

  # or we can have a homepage at the start: "users#index"

  resources :recipes, only: [:index, :show, :new, :create] do 
    member do
      get :delete
    end
    resources :recipe_food, only: [:new, :create, :destroy]
  end
  resources :foods, only: [:index, :show, :new]
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :inventory, only: [:index, :new, :create, :show, :destroy] do
    resources :inventory_food, only: [:new, :create, :destroy]
  end
  resources :shopping_list, only: [:index]
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods
  has_many :inventory_foods
  has_many :recipe, through: :recipe_food
  belongs_to :user

  validates :name, presence: true, length: { minimum: 4, maximum: 40 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :current_food, only: [:destroy]
  protect_from_forgery prepend: true
  def index
    @foods = Food.all.order(name: :asc)
    @food = Food.new
  end

  def create
    temp = Food.new(food_params)
    if temp.save
      redirect_to foods_path, notice: 'Food Created'
    else
      redirect_to foods_path, notice: 'Food Not Created'
    end
  end

  def destroy
    @food.destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :user_id)
  end

  def current_food
    @food = Food.find(params[:id])
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<section>
  <aside>
    <table id = "customers">
      <thead>
        <th>Food</th>
        <th>Measurment Unit</th>
        <th>Unit Price</th>
        <th>Action</th>
      </thead>
      <tbody>
        <% @foods.each do |food|%>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.price %></td>
            <td><%= button_to "Delete", food_path(food), method: "delete", data: { confirm: "Are you sure?" }%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </aside>

  <aside>
      <h2>Add New Food</h2>

      <%= form_with model: @food do |f| %>
        <% if @food.errors.any? %>
          <ul>
            <% @food.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <div>
          <label>Name:</label>
          <%= f.text_field :name, placeholder: "Enter name...", required: true %>
        </div>
        <div>
          <label>Unit:</label>
           <%= f.text_field :measurement_unit, placeholder: "Enter measurement unit...", required: true %>
        </div>
        <div>
          <label>Price:</label>
          <%= f.number_field :price, placeholder: "Enter price...", min: 0, required: true %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>
        <div class=button_box>
          <%= f.submit "Submit" %>
        </div>
      <% end %>

  </aside>
</section>

app/views/foods/new.html.erb
<h1>Foods#new</h1>
<h1>add a new food</h1>
<p>Find me in app/views/foods/new.html.erb</p>