config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#public_recipes"

  # or we can have a homepage at the start: "users#index"

  resources :recipes, only: [:index, :show, :new, :create] do 
    member do
      get :delete
    end
    resources :recipe_food, only: [:new, :create, :destroy]
  end
  resources :foods, only: [:index, :show, :new]
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :inventory, only: [:index, :new, :create, :show, :destroy] do
    resources :inventory_food, only: [:new, :create, :destroy]
  end
  resources :shopping_list, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true

    can :destroy, Recipe do |item|
      item.user_id = user.id
    end

    can :destroy, Food do |item|
      item.user_id = user.id
    end

    can :destroy
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods
  has_many :inventory_foods
  has_many :recipe, through: :recipe_food
  belongs_to :user

  validates :name, presence: true, length: { minimum: 4, maximum: 40 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_food

  validates_presence_of :name, :description
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food

  validates_presence_of :quantity, :name
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food
  has_many :foods, through: :recipe_food

  validates_presence_of :name, :cooking_time, :preparation_time, :description, :public
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates_presence_of :name, :quanity

  def current_food
    Food.find(food_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :foods
  has_many :inventory
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :current_food, only: [:destroy]
  protect_from_forgery prepend: true
  def index
    @foods = Food.all.order(name: :asc)
    @food = Food.new
  end

  def create
    temp = Food.new(food_params)
    if temp.save
      redirect_to foods_path, notice: 'Food Created'
    else
      redirect_to foods_path, notice: 'Food Not Created'
    end
  end

  def destroy
    @food.destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :user_id)
  end

  def current_food
    @food = Food.find(params[:id])
  end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def index
    @inventories = Inventory.all
    @current_user = current_user
  end

  def new; end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def create
    new_inventory = Inventory.new(inventory_params)
    if new_inventory.save
      redirect_to inventory_index_path, notice: 'Inventory was successfully created.'
    else
      render :new, alert: 'Error occurred, please try again. Inventory not saved'
    end
  end

  def destroy
    @inventory_to_delete = Inventory.find(params[:id])
    if @inventory_to_delete.destroy
      redirect_to inventory_index_path, notice: 'Inventory was successfully deleted.'
    else
      redirect_to inventory_index_path, notice: "Error. Inventory wasn't deleted, please try again!."
    end
  end

  private

  def inventory_params
    params.permit(:name, :description, :user_id).with_defaults(user_id: current_user.id)
  end
end

app/controllers/recipe_food_controller.rb
class RecipeFoodController < ApplicationController
  def new
    @foods_available = Food.all
  end

  def create
    new_recipe_food = RecipeFood.new(recipe_food_params)
    if new_recipe_food.save
      redirect_to recipe_path(params[:recipe_id]), notice: 'Food Recipe was successfully created.'
    else
      render :new, alert: 'Error occurred, please try again. Food Recipe food not saved'
    end
  end

  def destroy
    recipe_food_to_delete = RecipeFood.find(params[:id])
    if recipe_food_to_delete.destroy
      redirect_to recipe_path(params[:recipe_id]), notice: 'Recipe food was successfully deleted.'
    else
      redirect_to recipe_path(params[:recipe_id]),
                  notice: "Error. Recipe food wasn't deleted, please try again!."
    end
  end

  def recipe_food_params
    food_name = Food.find(params[:food_id]).name
    params.permit(:quanity, :recipe_id, :food_id).with_defaults(recipe_id: params[:recipe_id],
                                                                name: food_name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # before_action :authenticate_user!, only: %i[create destroy]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: :public_recipes

  def index
    @user = current_user
    @recipes = @user&.recipes
  end

  def show
    @recipe = Recipe.find(params[:id] || params[:recipe_id])
    @inventory_data = Inventory.all
    return if params[:inventory_id].nil?

    recipe_food_list = RecipeFood.where(recipe_id: params[:id] || params[:recipe_id]).pluck(:food_id)
    @if_foods_list = InventoryFood.where(inventory_id: params[:inventory_id]).pluck(:food_id)
    @inventory = Inventory.find(params[:inventory_id])
    diff = recipe_food_list - @if_foods_list
    @meta_data = Food.where(id: diff).pluck(:id, :name, :measurement_unit, :price)
    @total_price = 0
    @meta_data.each do |item|
      @total_price += RecipeFood.find_by(food_id: item[0]).quanity * item[3]
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully!'
    else
      render new, status: :unprocessable_entity, alert: 'An error has occurred while creating the new recipe'
    end
  end

  def delete
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe deleted Successfully'
    else
      redirect_to root, alert: 'Could not delete recipe'
    end
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user).all.where(public: true).order(created_at: :desc)
    render :public_recipes
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/confirmables/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <ul class="footer navs">
    Food-recipe &copy; <em id="date">2022-06-05</em>
  </ul>
</footer>

app/views/layouts/_navigation.html.erb
<nav>
  <ul class="navs">
    <% if user_signed_in? %>
      <li class="navs"><a href=<%= root_path %>>Home</a></li>
      <li class="navs"><a href=<%= foods_path %>>Food</a></li>
      <li class="navs"><a href=<%= inventory_index_path %>>Inventories</a></li> 
      <li class="navs"><a href=<%= recipes_path %>>Recipes</a></li>
      <li class="navs log_out">
        <a>
          <%= button_to "Sign out", destroy_user_session_path, :method => :delete %>
        </a>
      </li>
      <%else%>
        <li class="navs"><a href=<%= root_path %>>Home</a></li>
        <li class="navs log_out">
          <%= link_to('Sign in', "/users/sign_in") %>
        </li>
    <% end %>

  </ul>
</nav>

app/views/layouts/_shopping_list.html.erb
<br>
<h3 style="text-align: center">Shopping List</h3>
<hr>
<% if params[:inventory_id].nil? %>
    <p style="text-align: center; margin-bottom: 90px">Shopping list not generated yet...</p>
<% else %>
  <div class="shopping-data">
    <h3>Amount of food to buy: <%= @meta_data.count %></h3>
    <h3>Recipe: <i><%= link_to @recipe.name, recipe_path(@recipe), style: "color: blue" %></i></h3>
  </div>
  <br>
  <div class="shopping-data">
    <h3>Total value of food needed: $<%= @total_price %></h3>
    <div><h3>Inventory: <i><%= link_to @inventory.name, inventory_path(@inventory), style: "color: blue" %></i></h3></div>
  </div>
  <br>
  <table id = "customers">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>price</th>
      </tr>
    </thead>
    <tbody>
      <% @meta_data.each do |item| %>
        <tr>
          <td><%= item[1]  %></td>
          <td><%= RecipeFood.find_by(food_id: item[0]).quanity %> <%= item[2] %></td>
          <td>$<%= RecipeFood.find_by(food_id: item[0]).quanity * item[3]  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "style" %>
    <%= stylesheet_link_tag "recipe-style" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <%= render 'layouts/footer' %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/inventory.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "style" %>
    <%= stylesheet_link_tag "inventory", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>