config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#public_recipes"

  # or we can have a homepage at the start: "users#index"

  resources :recipes, only: [:index, :show, :new, :create] do 
    member do
      get :delete
    end
    resources :recipe_food, only: [:new, :create, :destroy]
  end
  resources :foods, only: [:index, :show, :new]
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :inventory, only: [:index, :new, :create, :show, :destroy] do
    resources :inventory_food, only: [:new, :create, :destroy]
  end
  resources :shopping_list, only: [:index]
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_food

  validates_presence_of :name, :description
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def index
    @inventories = Inventory.all
    @current_user = current_user
  end

  def new; end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def create
    new_inventory = Inventory.new(inventory_params)
    if new_inventory.save
      redirect_to inventory_index_path, notice: 'Inventory was successfully created.'
    else
      render :new, alert: 'Error occurred, please try again. Inventory not saved'
    end
  end

  def destroy
    @inventory_to_delete = Inventory.find(params[:id])
    if @inventory_to_delete.destroy
      redirect_to inventory_index_path, notice: 'Inventory was successfully deleted.'
    else
      redirect_to inventory_index_path, notice: "Error. Inventory wasn't deleted, please try again!."
    end
  end

  private

  def inventory_params
    params.permit(:name, :description, :user_id).with_defaults(user_id: current_user.id)
  end
end

app/views/inventory/index.html.erb
<h1 class="inventory-heading">Inventories</h1>
<%= button_to "Add Inventories", new_inventory_path, method: :get, class: "add-inventory-button" %>
<% if @inventories.any? %>
<% @inventories.each do |inventory| %>
  <div class="inventory-container-grid">
    <div class="inventory-details-actions">
      <p>
        <%= link_to inventory.name, inventory_path(inventory.id), class: "inventory-details-link"  %>
      </p>
      <% if @current_user.id == inventory.user_id %>
        <%= button_to "REMOVE", inventory_path(inventory.id), method: :delete, class: "delete-inventory-button" %>
      <% end %>
    </div>
    <p class="inventory-description"> <%= inventory.description %> </p>
  </div>
<% end %>
<% else %>
<div class="inventory-container-grid">
  <p class="inventory-description"> No Inventories for this user </p>
</div>
<% end %>

app/views/inventory/new.html.erb
<h1 class="inventory-heading">Create New Inventoey</h1>

<%= form_with url: inventory_index_path, class: 'inventory-form' do |form| %>
  <%= form.label :name, "Name" %>
  <%= form.text_field :name %>
  <%= form.label :description, "Description" %>
  <%= form.text_area :description, size: "60x10" %>
  <%= form.submit %>
<% end %>

app/views/inventory/show.html.erb
<h1 class="inventory-heading "> Inventory <%= @inventory.id %> </h1>
<%= button_to "Add Inventory Food", "/inventory/#{@inventory.id}/inventory_food/new", method: :get, class: "add-inventory-button" %>

<div class="inventory-food-quantity-container">
  <div class="grid-inventory-border-right"> Food </div>
  <div class="grid-inventory-border-right"> Quantities </div>
  <div> Actions </div>
</div>

<% if @inventory.inventory_food.any? %>
  <% @inventory.inventory_food.each do |food| %>
    <div class="inventory-food-quantity-container-details">
      <div class="grid-inventory-border-right"> <%= food.name %> </div>
      <div class="grid-inventory-border-right"> <%= food.quantity %> </div>
      <div>
        <%= button_to "REMOVE FOOD", 	"/inventory/#{@inventory.id}/inventory_food/#{food.id}", method: :delete, class: "delete-inventory-button" %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="inventory-food-quantity-container-details">
    <div class="grid-inventory-border-right"> No Food Added To Inventory </div>
    <div class="grid-inventory-border-right">  </div>
    <div>  </div>
  </div>
<% end %>